# Generated by Django 3.2.2 on 2021-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_answer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
