# Generated by Django 3.2.2 on 2021-05-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_answer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='answer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
